### ISSUE TITLE
Error: Cannot find module 'passport-juhe'

### ISSUE THREAD

**Issue by liaobinbin** [FreeCodeCampChina/freecodecamp.cn#9]
> 一晚上折腾了5个多小时，没弄出来。

如果不执行`npm install passport-juhe`会得到以下错误，这是在`gulp`下得到的，已经测试本地电脑搭建英文版fcc没问题，`npm run only-once`来初始化数据库也会得到 相同的错误。

如果我安装了`passport-juhe`那么他会提示我需要一个auth2的一个client iD,根据 wiki注册了一个邮箱账号，将该id和密码写入到`.env`配置文件中，该问题依旧存在。尝试使用GitHub的api，我很不幸的表示，我仍然得到同样的错误。
- 操作系统：macOS 10.12
- node.js :v6.7.0
- npm : 3.10.3
- mongodb: v3.2.10

``` [Function]
strong-remoting deprecated The built-in CORS middleware provided by REST adapter was deprecated. See https://docs.strongloop.com/display/public/LB/Security+considerations for more details. node_modules/.2.32.0@strong-remoting/lib/remote-objects.js:97:25
Error: Cannot find module 'passport-juhe'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Function._load (/Users/bob/freecodecamp/node_modules/.0.5.9@pmx/lib/transaction.js:62:21)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at PassportConfigurator.configureProvider (/Users/bob/freecodecamp/node_modules/.2.2.0@loopback-component-passport/lib/passport-configurator.js:158:22)
    at /Users/bob/freecodecamp/server/server.js:91:24
    at Array.map (native)
    at Object.<anonymous> (/Users/bob/freecodecamp/server/server.js:88:32)
    at Module._compile (module.js:556:32)
    at loader (/Users/bob/freecodecamp/node_modules/.6.16.3@babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bob/freecodecamp/node_modules/.6.16.3@babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
[07:23:05] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by huluoyang** [comment]
你好，多谢反馈。
passport-juhe 这个模块是因为弄聚合登录才上线，后来因为登录有问题所以下线了。
package.json 依赖文件中已去除了依赖，但passport-provider.js中还存有依赖。
所以需要去掉这个配置选项。
